#Settings for the application

# Whether to encrypt private keys
private_key_encryption: true

# Number of threads to use for processing wallets
threads: 1

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Hide wallet address in logs
hide_wallet_address_log: true

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Sleep time in hours after full execution of tasks
sleep_after_each_cycle_hours: 0

# Random pause between wallets in seconds
random_pause_between_wallets:
  min: 5
  max: 60

# Random pause between actions in seconds
random_pause_between_actions:
  min: 5
  max: 30

# Telegram Bot ID for notifications
tg_bot_id: ""

# You can find your chat ID by messaging @userinfobot or using https://web.telegram.org/. (example 1540239116)
tg_user_id: ""
